version: '3.8'

services:
  # MongoDB Database Service
  mongo:
    image: mongo:latest # Official MongoDB image use kiya
    container_name: supplimax-mongo
    restart: always
    ports:
      - "27017:27017" # Port 27017 ko expose kiya
    environment:
      # Database ka naam
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: supplimax-db 
    volumes:
      # Data ko container band hone ke baad bhi mehfooz rakhne ke liye
      - mongo-data:/data/db

volumes:
  mongo-data: